services:
    db:
        image: mysql:8.4
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

    backend:
        image: ghcr.io/franco2355/ingsoft3-tp01-backend:v0.1.0
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            APP_USER: ${APP_USER}
            APP_PASSWORD: ${APP_PASSWORD}
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy

    frontend:
        image: ghcr.io/franco2355/ingsoft3-tp01-frontend:v0.1.0
        environment:
            BACKEND_URL: http://backend:8000
        ports:
            - "3000:3000"
        depends_on:
            - backend

volumes:
    db_data:
